language: go
go:
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
  - tip
env:
  - GOARCH=386
  - GOARCH=amd64
matrix:
  allow_failures:
    - go: tip
install:
  - go get github.com/smartystreets/goconvey
  - go get github.com/pborman/uuid
  - go get github.com/go-errors/errors